# Generated by Django 3.2.4 on 2021-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='chatting',
            field=models.CharField(default='', max_length=300),
        ),
    ]
