# Generated by Django 3.2.3 on 2021-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_chatting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='images',
            field=models.ImageField(blank=True, default='../static/rental/img/daytoyear.jpg', null=True, upload_to='images/'),
        ),
    ]
