# Generated by Django 3.2 on 2021-06-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='../static/accounts/기본이미지.jpg', null=True, upload_to='accounts/'),
        ),
    ]
